import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import { signIn, signOut, useSession } from "next-auth/react";
import { useState } from "react";

import { api } from "../utils/api";
import LandingPage from "./LandingPage";

const Home = () => {
	const [triggerAnimate, setTriggerAnimate] = useState(false);

	return (
		<>
			<Head>
				<title>Dev2Dev</title>
				<meta name="description" content="Generated by create-t3-app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<main className="h-fit">
				<div
					className={`absolute inset-0 z-10 flex transform flex-col items-center justify-center bg-gradient-to-r from-[#7031c9] to-[#15162c] text-white transition-transform duration-500 ${
						triggerAnimate ? "-translate-y-full " : ""
					}`}
				>
					<h3 className="text-4xl font-bold text-white">
						Welcome to Dev2Dev
					</h3>
					<div className="mt-6 mb-9 w-full text-center text-2xl font-bold text-white">
						Dev2Dev is a website that pairs developers who need
						help,
						<br /> with more experienced developers who have
						expertise specific to the problems <br /> they&apos;re
						trying to solve! To get started, click the button below!
					</div>
					<button
						type="button"
						onClick={() => setTriggerAnimate(true)}
						className="inline-flex items-center rounded-md border border-transparent bg-indigo-100 px-6 py-3 text-base font-medium text-indigo-700 hover:bg-indigo-200 focus:outline-none focus:ring-2 focus:ring-indigo-500 focus:ring-offset-2"
					>
						Get Started
					</button>
					{/* <LandingPage /> */}
				</div>
				<div className="absolute inset-0 z-0 flex">
					<div className="flex w-[50%] flex-col items-center justify-center gap-6 bg-gradient-to-b from-[#7031c9] to-[#151fd5]">
						<h2 className="text-6xl font-bold text-white">
							I have a question!
						</h2>
						<Link
							type="button"
							href="/askquestion"
							className="inline-flex items-center rounded-md border border-transparent bg-indigo-600 px-6 py-3 text-base font-medium text-white shadow-sm hover:bg-indigo-700 focus:outline-none focus:ring-2 focus:ring-indigo-500 focus:ring-offset-2"
						>
							Ask a question
						</Link>
					</div>
					<div className="flex w-[50%] flex-col items-center justify-center gap-6 bg-gradient-to-b from-[#2e026d] to-[#15162c]">
						<h2 className="text-6xl font-bold text-white">
							I have an answer!
						</h2>
						<Link
							href="/answerquestion"
							type="button"
							className="inline-flex items-center rounded-md border border-transparent bg-indigo-800 px-6 py-3 text-base font-medium text-white shadow-sm hover:bg-indigo-700 focus:outline-none focus:ring-2 focus:ring-indigo-500 focus:ring-offset-2"
						>
							Answer a question
						</Link>
					</div>
				</div>
			</main>
		</>
	);
};

export default Home;
